use_frameworks!

platform :ios, '10.0'

target 'Util_V_Example' do
  pod 'Util_V', :path => '../'

  target 'Util_V_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.2.0'
    pod 'Nimble', '~> 10.0.0'
  end
end
